
* Bruce Ravel's XAS Education Materials

** Talks

These folders contain the LaTeX source for my talks.  All talks use
LaTeX and [[https://bitbucket.org/rivanvx/beamer/wiki/Home][the Beamer LaTeX class]].  All images are included, usually as
.png or .jpg files.  Source material (e.g. GIMP .xcf, LibreOffice .odg,
Xfig .fig) are deposited for some images.

PDF files can be found in [[https://github.com/bruceravel/XAS-Education/downloads][downloads area]].

 | *folder*   | *title of talk*                                                                 |
 |------------+---------------------------------------------------------------------------------|
 | ATEA       | Advanced Topics In EXAFS Analysis                                               |
 | Experiment | The XAFS Experiment: Instrumentation, Sample Preparation, and Experiment Design |
 | iiss       | Introduction to Inner Shell Spectroscopies                                      |
 | noxtal     | Modeling non-crystalline samples                                                |
 | pimst      | A Practical Introduction to Multiple Scattering Theory                          |
 | selfabs    | Understanding self-absorption in ﬂuorescence XAS                                |

** Examples

These folders contain the XAS and structural data used in the talks.

 | *folder*          | *contents*                                                             |
 |-------------------+------------------------------------------------------------------------|
 | Cu metal          | Copper foil at 3 temperatures + crystal data                           |
 | FeS2              | FeS2 transmission exafs + crystal data                                 |
 | Germanium         | Crystalling and amorphous Ge data + crystal data                       |
 | Methyltin         | Monomethyl tin trichloride + dimethyl tin dichloride + structure data  |
 | Self Absorption   | Data demonstrating self-absorption: Fe, Fe73Ga27, sulfate, zirconolite |
 | Uranyl on Biomass | uranyl acetate in equillibrium with biomass                            |

** Other folders

 + ~sty/~: Copies of my customizations of the [[http://recherche.noiraudes.net/fr/LaTeX.php][progressbar Beamer theme]] by Sylvain Bouveret.


To use the style files, the ~TEXINPUTS~ environment variable must be
set with a line like this either in the ~.bashrc~ file or at the
command line:

    : export TEXINPUTS=".:$HOME/TeX/XAS-Education/sty/:"

where ~$HOME/TeX~ would be replaced by the location of the local XAS-Education repository.



** License

Unless otherwise indicated, all these talks are licensed under the [[http://creativecommons.org/][Creative Commons]]
[[http://creativecommons.org/licenses/by-sa/3.0/][Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)]] license.

This is a human-readable summary of the [[http://creativecommons.org/licenses/by-sa/3.0/legalcode][Legal Code (the full license)]].
 
You are free:

 + *to Share* — to copy, distribute and transmit the work
 + *to Remix* — to adapt the work
 + to make commercial use of the work

Under the following conditions:

 + *Attribution* — You must attribute the work in the manner specified
   by the author or licensor (but not in any way that suggests that they
   endorse you or your use of the work).

 + *Share Alike* — If you alter, transform, or build upon this work,
   you may distribute the resulting work only under the same or
   similar license to this one.

With the understanding that:

 + *Waiver* — Any of the above conditions can be waived if you get permission from the copyright holder.
 + *Public Domain* — Where the work or any of its elements is in the public domain under applicable law, that status is in no way affected by the license.
 + *Other Rights* — In no way are any of the following rights affected by the license:
    + Your fair dealing or fair use rights, or other applicable copyright exceptions and limitations;
    + The author's moral rights;
    + Rights other persons may have either in the work itself or in how the work is used, such as publicity or privacy rights.
 + *Notice* — For any reuse or distribution, you must make clear to others the license terms of this work. The best way to do this is with a link to this web page.
